const btn1 = document.getElementById("btn1")
const btn2 = document.getElementById("btn2")
const btn3 = document.getElementById("btn3")
const contant1 = document.getElementById("contant1")
const contant2 = document.getElementById("contant2")
const contant3 = document.getElementById("contant3")